# Generated by Django 4.2.6 on 2023-11-18 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionpaper', '0001_initial'),
    ]

    operations = [
    ]
